services:
   db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: essia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

   backend:
     build:
       context: ./backend
       dockerfile: Dockerfile
     container_name: essia_backend_api
     environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/essia_db
       SPRING_DATASOURCE_USERNAME: postgres
       SPRING_DATASOURCE_PASSWORD: postgres
     ports:
       - "8080:8080"
     depends_on:
       - db

   frontend:
     build:
       context: ./frontend
       dockerfile: Dockerfile
     container_name: essia_frontend
     ports:
       - "8081:8080"
     depends_on:
       - backend

volumes:
  postgres_data: